import json
import sqlite3
from datetime import datetime, timezone
from typing import Dict, List, Optional


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def export_json_rulepack(conn: sqlite3.Connection) -> Dict:
    # 1. Сигнатуры
    sigs_rows = conn.execute("SELECT * FROM signatures").fetchall()
    by_kind = {}
    for r in sigs_rows:
        row = dict(r)
        kind = row.get("kind", "other")
        by_kind.setdefault(kind, []).append(row)

    # 2. Бренды
    brands_rows = conn.execute(
        "SELECT DISTINCT brand, in_target FROM brands WHERE brand IS NOT NULL"
    ).fetchall()
    target_brands = [dict(b) for b in brands_rows]

    # 3. Кампании
    try:
        camp_rows = conn.execute("SELECT * FROM campaigns").fetchall()
        campaigns = [dict(c) for c in camp_rows]
    except Exception:
        campaigns = []

    # 4. Вредоносные артефакты (хэши)
    art_rows = conn.execute(
        "SELECT DISTINCT kind, md5, sha256 FROM artifacts WHERE sha256 IS NOT NULL"
    ).fetchall()
    attachment_hashes = [dict(a) for a in art_rows]

    # Сборка компактных правил
    brand_feature_rules = []
    for sig in by_kind.get("brand_feature", []):
        val = sig.get("signature", "")
        meta = json.loads(sig["meta"]) if sig.get("meta") else {}
        brand_feature_rules.append({
            "rule_id": f"RULE_BRAND_{sig['id']}",
            "brand_domain_pair": val,
            "in_target": meta.get("in_target", False),
            "domain_mismatch": meta.get("domain_mismatch", True),
            "score": 8.5 if meta.get("in_target") else 6.0,
            "reason_code": "BRAND_IMPERSONATION_TARGET" if meta.get("in_target") else "BRAND_IMPERSONATION"
        })

    dom_template_rules = []
    for sig in by_kind.get("dom_template", []):
        meta = json.loads(sig["meta"]) if sig.get("meta") else {}
        dom_template_rules.append({
            "rule_id": f"RULE_DOM_{sig['id']}",
            "dom_hash": sig.get("signature"),
            "score": 9.0,
            "reason_code": "REUSED_DOM_TEMPLATE"
        })

    url_template_rules = []
    for sig in by_kind.get("url_template", []):
        url_template_rules.append({
            "rule_id": f"RULE_URL_{sig['id']}",
            "pattern": sig.get("signature"),
            "score": 7.0,
            "reason_code": "SUSPICIOUS_URL_PATH_TEMPLATE"
        })

    reason_codes_list = list(set(s.get("signature") for s in by_kind.get("reason_code", [])))

    return {
        "manifest": {
            "format": "threat_intelligence_rules",
            "version": "1.0.0",
            "exported_at": _now_iso(),
            "total_rules": len(brand_feature_rules) + len(dom_template_rules) + len(url_template_rules),
            "active_campaigns_count": len(campaigns),
        },
        "target_brands": target_brands,
        "campaigns": campaigns,
        "brand_rules": brand_feature_rules,
        "dom_template_rules": dom_template_rules,
        "url_template_rules": url_template_rules,
        "attachment_fingerprints": attachment_hashes,
        "active_reason_codes": reason_codes_list,
    }


def export_rspamd_rules(conn: sqlite3.Connection) -> str:
    rulepack = export_json_rulepack(conn)
    lines = [
        "-- ==========================================================================",
        "-- Rspamd Rules generated by Phishing Threat Intelligence Pipeline",
        f"-- Exported: {rulepack['manifest']['exported_at']}",
        f"-- Total Active Rules: {rulepack['manifest']['total_rules']}",
        "-- ==========================================================================",
        "",
        "local rspamd_config = rspamd_config or {}",
        "",
        "-- 1. Brand Impersonation Rules",
    ]

    for b in rulepack.get("brand_rules", []):
        clean_id = b["rule_id"]
        pair = b["brand_domain_pair"]
        score = b["score"]
        lines.append(f'rspamd_config["{clean_id}"] = {{')
        lines.append(f'  score = {score},')
        lines.append(f'  description = "Brand mismatch detected: {pair}",')
        lines.append(f'  group = "phishing"')
        lines.append('}')

    lines.append("\n-- 2. DOM Template Rules")
    for d in rulepack.get("dom_template_rules", []):
        clean_id = d["rule_id"]
        h = d["dom_hash"]
        lines.append(f'rspamd_config["{clean_id}"] = {{')
        lines.append(f'  score = {d["score"]},')
        lines.append(f'  description = "Known phishing DOM skeleton hash: {h}",')
        lines.append(f'  group = "phishing"')
        lines.append('}')

    return "\n".join(lines)


def export_yara_rules(conn: sqlite3.Connection) -> str:
    artifacts = conn.execute("SELECT DISTINCT kind, sha256, md5 FROM artifacts WHERE sha256 IS NOT NULL").fetchall()

    lines = [
        "/*",
        "  YARA Signatures generated by Phishing Threat Intelligence Pipeline",
        f"  Exported: {_now_iso()}",
        "*/",
        "",
    ]

    for idx, a in enumerate(artifacts):
        sha = a["sha256"]
        kind = a["kind"]
        rule_name = f"Phish_Artifact_{kind}_{idx+1}"
        lines.append(f"rule {rule_name} {{")
        lines.append("  meta:")
        lines.append(f'    description = "Known malicious phishing artifact ({kind})"')
        lines.append(f'    sha256 = "{sha}"')
        lines.append(f'    md5 = "{a["md5"] or ""}"')
        lines.append("  condition:")
        lines.append(f'    hash.sha256(0, filesize) == "{sha}"')
        lines.append("}\n")

    return "\n".join(lines)
